// =============================================================================
// AIStudyHub.DAL - Entities Directory (PLACEHOLDER)
// =============================================================================
//
// This folder will contain entity classes generated by Scaffold-DbContext.
// DO NOT create entity classes manually.
//
// Expected entities after scaffolding:
//   - User.cs
//   - Role.cs
//   - Subject.cs
//   - Document.cs
//   - Tag.cs
//   - DocumentTag.cs
//   - ChatSession.cs
//   - ChatMessage.cs
//
// =============================================================================
