// =============================================================================
// AIStudyHub.DAL - AppDbContext (PLACEHOLDER)
// =============================================================================
//
// This file is a PLACEHOLDER.
//
// DO NOT implement AppDbContext manually.
// It will be auto-generated by running the Scaffold-DbContext command
// after the SQL Server database schema is created.
//
// ─── SCAFFOLD COMMAND ───────────────────────────────────────────────────────
//
// In Visual Studio → Package Manager Console:
//   1. Set Default Project to: AIStudyHub.DAL
//   2. Run:
//
// Scaffold-DbContext "Server=.;Database=AIStudyHub;Trusted_Connection=True;TrustServerCertificate=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities -Context AppDbContext -ContextDir . -DataAnnotations -Force
//
// ─── USING .NET CLI ─────────────────────────────────────────────────────────
//
// dotnet ef dbcontext scaffold "Server=.;Database=AIStudyHub;Trusted_Connection=True;TrustServerCertificate=True" Microsoft.EntityFrameworkCore.SqlServer --output-dir Entities --context AppDbContext --context-dir . --data-annotations --force --project AIStudyHub.DAL --startup-project AIStudyHub.API
//
// ─── AFTER SCAFFOLDING ──────────────────────────────────────────────────────
//
// 1. This file will be replaced by the generated AppDbContext.cs
// 2. Entity classes will appear in the Entities/ folder
// 3. Update GenericRepository<T> to use AppDbContext instead of DbContext
// 4. Update repository implementations to accept AppDbContext
// 5. Register AppDbContext in Program.cs
//
// =============================================================================
